services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    command:
      - --log-bin=mysqlId-bin
      - --log_bin_trust_function_creators=1
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: